<link rel="stylesheet" type="text/css" href="lib/pnk/pnk.css?">
<link rel="stylesheet" type="text/css" href="lib/select2/select2.min.css">
<div class='pnk-table' pnk-src='src/gila-shop/tables/shop_product' pnk-table="shop_product" id='tproducts'></div>

<?=view::script('lib\jquery\jquery-3.3.1.min.js')?>
<?=view::script('lib\pnk\pnk-1.3.js')?>
<?=view::script('lib\select2\select2.min.js')?>
<?=view::script('src\core\assets\admin\media.js')?>
<script>
PNK.field_types.media = {
    displayInput: function(field, value) {
        return '<input class="g-input" onclick="open_media_gallery(this)" value="'+value+'" name="image">';
    }
}
pnk_populate_tables(document);
</script>
